name: Broken Link Checker

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 1 * * 3'  # Mittwochs um 1 Uhr
  workflow_dispatch:

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Wait for deployment
        run: sleep 30
      - name: Check links with modern action
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --exclude-path ./_site
            --exclude ".*feed\.xml.*"
            --exclude ".*intent/.*"
            --exclude ".*twitter\.com.*"
            --exclude ".*x\.com.*"
            --exclude ".*facebook\.com.*"
            --exclude ".*linkedin\.com.*"
            --exclude ".*bsky\.app.*"
            --no-progress
            --verbose
            https://www.kmupowersuite.com/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
