name: Core Web Vitals Monitor

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 1 * * 3'  # Mittwochs um 1 Uhr
  workflow_dispatch:

jobs:
  web-vitals:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Lighthouse CI (richtige Web Vitals Messung)
        run: npm install -g @lhci/cli
      - name: Wait for deployment
        run: sleep 30
      - name: Run Lighthouse for Core Web Vitals
        run: |
          npx lhci autorun \
            --collect.url="https://www.kmupowersuite.com/" \
            --collect.settings.chromeFlags="--no-sandbox" \
            --collect.numberOfRuns=3 \
            --assert.preset="lighthouse:no-pwa" \
            --upload.target=temporary-public-storage
        continue-on-error: true
      - name: Add job summary
        run: |
          echo "### Core Web Vitals" >> $GITHUB_STEP_SUMMARY
          echo '\n<details><summary>Ergebnisse</summary>\n' >> $GITHUB_STEP_SUMMARY
          echo "(siehe Log f\u00fcr Details)" >> $GITHUB_STEP_SUMMARY
          echo '\n</details>' >> $GITHUB_STEP_SUMMARY
        shell: bash
