name: Lighthouse SEO & Performance Audit

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 1 * * 3'  # Mittwochs um 1 Uhr
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      
      - name: Wait for deployment
        run: sleep 30  # Kurz warten bis Deployment vollständig propagiert ist
      
      - name: Run Lighthouse CI against live site
        id: lighthouse
        run: |
          npx lhci autorun \
            --collect.url="https://www.kmupowersuite.com/" \
            --upload.target=temporary-public-storage > lhci-output.txt || true
        continue-on-error: true
      - name: Add job summary
        run: |
          echo "### Lighthouse Audit" >> $GITHUB_STEP_SUMMARY
          echo '\n<details><summary>Ergebnis (gekürzt)</summary>\n' >> $GITHUB_STEP_SUMMARY
          head -n 50 lhci-output.txt >> $GITHUB_STEP_SUMMARY
          echo '\n</details>' >> $GITHUB_STEP_SUMMARY
        shell: bash
