name: Security Scan

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 1 * * 3'  # Mittwochs um 1 Uhr
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'
          scan-ref: '.'
        continue-on-error: true
      - name: Check for exposed secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
        continue-on-error: true
