name: Comprehensive SEO Audit

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
  schedule:
    - cron: '0 1 * * 3'  # Mittwochs um 1 Uhr
  workflow_dispatch:

jobs:
  seo-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Check meta tags
        run: |
          curl -s https://www.kmupowersuite.com/ | grep -i "<title\|<meta.*description\|<meta.*keywords" || true
        continue-on-error: true
      - name: Check structured data
        run: |
          curl -s "https://search.google.com/test/rich-results?url=https://www.kmupowersuite.com/" || true
        continue-on-error: true
      - name: Check Open Graph and Twitter Cards
        run: |
          curl -s https://www.kmupowersuite.com/ | grep -i "og:\|twitter:" || true
        continue-on-error: true
