name: Uptime Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Alle 30 Minuten
  workflow_dispatch:

jobs:
  uptime-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check website availability
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://www.kmupowersuite.com/ | grep -E '200|201|301|302'