name: Uptime Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Alle 30 Minuten
  workflow_dispatch:

jobs:
  uptime-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check website availability
        id: check
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://www.kmupowersuite.com/)
          echo "Status: $STATUS"
          if [[ "$STATUS" =~ ^(200|201|301|302)$ ]]; then
            echo "✅ Website is UP ($STATUS)"
          else
            echo "❌ Website is DOWN ($STATUS)"
            exit 1
          fi
      - name: Add job summary
        run: |
          if [[ "$STATUS" =~ ^(200|201|301|302)$ ]]; then
            echo "### Uptime Check" >> $GITHUB_STEP_SUMMARY
            echo "✅ Website is UP ($STATUS)" >> $GITHUB_STEP_SUMMARY
          else
            echo "### Uptime Check" >> $GITHUB_STEP_SUMMARY
            echo "❌ Website is DOWN ($STATUS)" >> $GITHUB_STEP_SUMMARY
          fi
        shell: bash